### ISSUE TITLE
svg doesn't have full blueprint grid

### ISSUE THREAD

**Issue by paulirish** [ChromeDevTools/devtools-logo#1]
i'm not seeing the blueprint gridlines in the SVG.

@maax to triage

**Comment by paulirish** [comment]
@maax do you still have these assets? Would love to sort out the svg

**Comment by maax** [comment]
Hi Paul! I fixed the grid issue, included the Sketch file and added a new, optimized 48dp version.

**Comment by paulirish** [comment]
You're a pro.
Thanks man!
