### ISSUE TITLE
What license is this under?

### ISSUE THREAD

**Issue by auchenberg** [ChromeDevTools/devtools-logo#2]
What license is this under? BSD like the rest of Chromium, https://src.chromium.org/viewvc/chrome/trunk/src/LICENSE?

**Comment by maax** [comment]
It's licensed under a [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/) (see readme page).

**Comment by auchenberg** [comment]
Thanks. I need to open my eyes.
